import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from 'next/font/google';
import Menu from "@/components/Sidebar";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Holiwise test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} antialiased`}
      >
        <Header />
        <div className="flex">
          <Sidebar />
          <section className="ml-[0] lg:ml-[240px] sm:w-[calc(100%-240px)]">
            {children}
          </section>
        </div>
        
      </body>
    </html>
  );
}
